#!/system/bin/sh
insmod /system/lib/modules/symsearch.ko
insmod /system/lib/modules/overclock.ko

echo 60 > /proc/overclock/max_vsel
echo 900000 > /proc/overclock/max_rate

#echo "5 900000000 60" > /proc/overclock/mpu_opps
 echo "4 700000000 49" > /proc/overclock/mpu_opps
 echo "3 500000000 44" > /proc/overclock/mpu_opps
 echo "2 250000000 33" > /proc/overclock/mpu_opps
#echo "1 125000000 32" > /proc/overclock/mpu_opps

#echo "0 900000" > /proc/overclock/freq_table
 echo "1 700000" > /proc/overclock/freq_table
 echo "2 500000" > /proc/overclock/freq_table
 echo "3 250000" > /proc/overclock/freq_table

insmod /system/lib/modules/cpufreq_stats.ko

insmod /system/lib/modules/cpufreq_interactive.ko
insmod /system/lib/modules/cpufreq_smartass.ko
insmod /system/lib/modules/cpufreq_conservative.ko

echo interactive > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

#echo conservative > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
#echo 125000 > /sys/devices/system/cpu/cpu0/cpufreq/conservative/sampling_rate
#echo 25 > /sys/devices/system/cpu/cpu0/cpufreq/conservative/freq_step

