#!/system/bin/sh

# Enable cpufreq stats.
# As the freq table has been already altered by the 10overclock script,
# let's suppose it won't be modified again later, so there is a chance
# that the stats will be valid from now on.
# Do the insmod here and not directly at the end of 10overclock, because
# some users may be already using customized backup of 10overclock.
insmod /system/lib/modules/cpufreq_stats.ko

